### ISSUE TITLE
HEART_BEAT_TIMEOUT cannot be caused by `:heart.set_cmd("disable")`

### ISSUE THREAD

**Issue by pojiro** [nerves-project/nerves_heart#12]
### Environment

* Elixir version (`elixir -v`):

```
elixir -v
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
```

* Nerves environment: (`mix nerves.env --info`)

```
mix nerves.env --info
==> nerves
==> bbb_test
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_bbb
  Vsn:         2.13.4
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, [make_args: ["source", "all", "legal-info"]]}

  Pkg:         nerves_system_br
  Vsn:         1.18.6
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_armv7_nerves_linux_gnueabihf
  Vsn:         1.5.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.8.5
  Type:        toolchain_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   bbb
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     bbb
  toolchain:  /home/pojiro/.nerves/artifacts/nerves_toolchain_armv7_nerves_linux_gnueabihf-linux_x86_64-1.5.0
  system:     /home/pojiro/.nerves/artifacts/nerves_system_bbb-portable-2.13.4
  app:        .

|nerves_bootstrap| Loadpaths End
```

* Additional information about your host, target hardware or environment that
  may help

```
MIX_ENV=dev
MIX_TARGET=bbb
```

### Current behavior

Out of curiosity, I am looking into the behavior of nerves_heart with BBB/nerves_system_bbb.

`-heart -env HEART_BEAT_TIMEOUT 30` is written in rel/vm.args.eex( this is default settings, I haven't changed).

On the target console, we can confirm heart process by ps command, like below
`  137 root      1820 S    heart -pid 117 -ht 30`

I confirmed if I changed the value of HEART_BEAT_TIMEOUT 30 to 45, it changes the `-ht` option value 30 to 45. so it works. 
 
But `:heart.get_cmd/0` shows below, `timeout` value is 120. 
```
iex(18)> :heart.get_cmd |> then(fn {:ok, msg} -> IO.puts msg end)
program_name=nerves_heart
program_version=1.0.0
identity=OMAP Watchdog
firmware_version=0
options=0x00008180
time_left=118
pre_timeout=0
timeout=120
last_boot=power_on
```

If I invoked `:heart.set_cmd("disable")`, the targets reboot after 120s as displayed.

### Expected behavior

HEART_BEAT_TIMEOUT should be set appropriately in BBB as well. 
But I don't know why this happens, are there any restrictions on settings for BBB?

**Comment by pojiro** [comment]
I also confirmed this happens on raspi3, 

```
 113 root      1656 S    heart -pid 83 -ht 30
```

```
iex(4)> :heart.get_cmd |> then(fn {:ok, msg} -> IO.puts msg end)
program_name=nerves_heart
program_version=1.0.0
identity=Broadcom BCM2835 Watchdog timer
firmware_version=0
options=0x00008180
time_left=11
pre_timeout=0
timeout=15
last_boot=power_on
```

**Comment by pojiro** [comment]
Now I understand why this happens.

`:heart.set_cmd("disable")` makes `pet_watchdog` do nothing by below.
https://github.com/nerves-project/nerves_heart/blob/a8334ac0b3b7480cc3e11276b46e7c594d0b8d2a/src/heart.c#L355-L357

Erlang VM's HEARTBEAT cannot be stopeed, so `last_received` is still update even if `:heart.set_cmd("disable")` was invoked.

https://github.com/nerves-project/nerves_heart/blob/a8334ac0b3b7480cc3e11276b46e7c594d0b8d2a/src/heart.c#L344-L347

Therefore, R_TIMEOUT does not return form `message_loop`.

https://github.com/nerves-project/nerves_heart/blob/a8334ac0b3b7480cc3e11276b46e7c594d0b8d2a/src/heart.c#L322-L326


### Wraping up

* nerves_heart doesn't change the watchdog timeout value
* `:heart.set_cmd("disable")` causes watchdog timeout not heartbeat timeout.
* Watchdog timeout value > Heartbeat timeout value, stopping HEARTBEAT will result in heartbeat timeout.
* Watchdog timeout value < Heartbeat timeout value, stopping HEARTBEAT will result in watchdog timeout.

**Comment by fhunleth** [comment]
@pojiro Thank you for writing this up. 

I have thought that `nerves_heart` could be improved to make debugging heartbeat and watchdog-initiated reboots easier to debug. Every time I have had an issue with the watchdog, it has been due to a mistake that I made, but it would be nice to have more information. I will add issues that would help me. If you have ideas, please feel free to add them too.
